---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: metrics-demo
  namespace: dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: metrics-pod 
        image: quay.io/brice/metrics-demo:v4-subscription-service
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
